### ISSUE TITLE
Settings and QR Code Scan Functions Not Working on android Version

### ISSUE THREAD

**Issue by MarkDMatzke** [kitswas/VirtualGamePad-Mobile#2]
Hi! I wanted to report a few issues I encountered with the VirtualGamePad-Mobile app. It seems that the Settings button, as well as the QR code scan and connect functions, aren’t working on the Android version. I've been trying different remote solutions for RetroArch, but unfortunately, these features aren't responding as expected.

I'm not sure how to fix this, but I wanted to leave a note here so others are aware before they download. Thanks, and hopefully this helps improve the experience for everyone! 😊

**Comment by kitswas** [comment]
The current main branch for both the [PC](https://github.com/kitswas/VirtualGamePad-PC) and [Mobile](https://github.com/kitswas/VirtualGamePad-Mobile) app have improvements with some customization support.  
The above issues have been handled.

I wanted to release a new version for the PC and Mobile apps together, but the PC version needs more improvements.  
I'll look into creating a new release for the Mobile app soon.

**Comment by MarkDMatzke** [comment]
Thank you for the update and the hard work on improving the project!

So far, I haven’t encountered any issues with the PC side, which I appreciate being straightforward to use since it runs directly from the ZIP without requiring installation.

However, on the mobile side (I redownloaded the app to confirm), I’m still having trouble with the QR code scan not functioning and the "Connect" button not working. Even when I manually input the server information (which the PC app confirmed as running), it didn’t establish a connection.

I hope this additional feedback helps as you prepare the next release! Thanks again for your efforts! 😊

**Comment by kitswas** [comment]
@MarkDMatzke Check the new release.
https://github.com/kitswas/VirtualGamePad-Mobile/releases/tag/v0.2.0

Feel free to reopen this if it does not address your issues.

**Comment by MarkDMatzke** [comment]
Finally, the settings are working now. However, the 'Scan QR Code' feature still doesn’t function. Additionally, when trying to connect the server information from the Windows application to the phone APK, it fails to establish a connection. Thanks anyway! 😊

**Comment by kitswas** [comment]
> when trying to connect the server information from the Windows application to the phone APK, it fails to establish a connection.

There could be a lot of reasons for this.
Try creating a hotspot on your phone and connect your PC to it. (or vice-versa)

Additionally, remember to try all the interfaces shown on the server. (You can click to switch between addresses)

![image](https://github.com/user-attachments/assets/6b4858b6-1a76-45c6-a8d9-5c23c5c0249b)


Remember to use the [latest server(v0.2.0).](https://github.com/kitswas/VirtualGamePad-PC/releases/tag/v0.2.0)

**Comment by kitswas** [comment]
> However, the 'Scan QR Code' feature still doesn’t function.

Which phone? (Manufacturer, model, Android version)

**Comment by MarkDMatzke** [comment]
Also, there was one listed on the IP server list.

**Comment by kitswas** [comment]
** Try creating a hotspot on your phone and connect your PC to it. (or vice-versa)**

Did you try this?

**Comment by MarkDMatzke** [comment]
For another application I had, sadly, I'm at the library, so most applications don't work. Runescape finally works, though. Sigh, I should have bought a controller so I could enjoy these games again. Thanks again, and don't worry about it.
